name: Prettier

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  check-prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn

      - name: Check code formatting
        run: yarn prettier:check
